Add getraworphanpool rpc
gandrewstone/bitcoin pull request #1421
Opened 2018-10-22 12:13 UTC by ptschip

This returns all the transaction hashes for transactions currently in
the orphanpool.

2018-10-23 10:27 UTC, awemany requested changes

2018-10-23 10:27 UTC, awemany commented on src/txorphanpool.h
> -    //! Do we already have this orphan in the orphan pool
Are you sure about this and the other changes removing the exclamation mark? It is the marker as it is used by `doxygen` for generating the code docs.

2018-10-23 12:53 UTC, ptschip commented
 I don't really have any feeling one way or the other, was just trying
to be consistent with our comments everywhere else. I can change back.

On 23/10/2018 3:27 AM, awemany wrote:
>
> *@awemany* requested changes on this pull request.
>
> ------------------------------------------------------------------------
>
> In src/txorphanpool.h
> <https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/1421#discussion_r227327330>:
>
> > @@ -39,31 +39,34 @@ class CTxOrphanPool
>  
>      CTxOrphanPool();
>  
> -    //! Do we already have this orphan in the orphan pool
>
> Are you sure about this and the other changes removing the exclamation
> mark? It was the marker as used by |doxygen| when it generates the docs.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/1421#pullrequestreview-167340693>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMRF0Nzyq1ptsIeBgWu49ECKX2f5W6EBks5unu8fgaJpZM4XzRQh>.
>

2018-10-23 14:31 UTC, ptschip commented on src/txorphanpool.h
> -    //! Do we already have this orphan in the orphan pool
ok done

2018-10-27 11:42 UTC, awemany commented
Great @ Doxygen comments. Am I too pedantic if I also suggest that this should have a simple RPC test? :-)

2018-10-27 12:18 UTC, ptschip commented
there is one , at the very top

On 27/10/2018 4:42 AM, awemany wrote:
>
> Great @ Doxygen comments. Am I too pedantic if I also suggest that
> this should have a simple RPC test? :-)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/1421#issuecomment-433613350>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMRF0Nrj6dtG5FzALRv-B57oEhjSCv4Yks5upEaLgaJpZM4XzRQh>.
>

2018-10-27 13:10 UTC, awemany commented
Fair enough! I was thinking maybe to get something into the orphan pool and test that it appears in the RPC. (But I don't think that's worth blocking the PR)

2018-10-29 16:46 UTC, merged