Initialize struct ThinBlockQuickStats fields to 0 upon construction
gandrewstone/bitcoin pull request #1768
Opened 2019-06-03 14:53 UTC by sickpig

2019-06-03 16:56 UTC, ptschip requested changes
You might as well do the same in graphene.h and compactblocks.h

2019-06-07 16:44 UTC, sickpig commented
@ptschip working on it. I'm thinking to remove a bunch of code dup since `*BlockQuickStats` are basically the same struct declared multiple times once for each propagation techniques.

2019-06-11 15:49 UTC, sickpig commented
updated with initialization also for Compact Blocks and Graphene.

2019-06-11 17:57 UTC, ptschip approved these changes

2019-06-12 12:23 UTC, merged