[WIP] Gradually decay assigned misbehavior over time
gandrewstone/bitcoin pull request #2143
Opened 2020-03-31 17:58 UTC by ptschip

Decay misbehavior over a 4 hour window of time.

Also, updated a few other variables and made them atomic since we don't lock anything when we assign misbehavior.

2020-04-01 17:59 UTC, ptschip commented
Taking out of WIP:

I've tested this and verified that the misbehavior dynamically updates in QT, but if anyone wants to test this you can go into net.h and set the nMisbehavior{80}; so that when each peer connects it automatically has some misbehavior assinged.  Then let it run for an hour or so and check your peers misbehavior which should be less than when you started.

2020-04-01 19:24 UTC, ptschip commented
all tests passed although travis does not show that

2020-04-02 09:52 UTC, sickpig commented
Even thou the travis checks are failed, they passed, check

https://travis-ci.org/github/BitcoinUnlimited/BitcoinUnlimited/builds/669815884

2020-04-06 20:38 UTC, gandrewstone requested changes

2020-04-06 20:38 UTC, gandrewstone commented on src/dosman.cpp
> +    double prior = pNode->nMisbehavior.load();
compare_exchange_weak allows the programmer to make arbitrary changes atomically.  But if you just want to atomically add, you can use the fetch_add or operator+= member functions.  This is a lot cleaner.
https://en.cppreference.com/w/cpp/atomic/atomic/operator_arith2
https://en.cppreference.com/w/cpp/atomic/atomic/fetch_add

2020-04-06 20:38 UTC, gandrewstone commented on src/qt/clientmodel.cpp
> +    // Update all misbehaviors
I think you put this in the QT code only because the bitcoind code updates when misbehaving happens, and there is no other display of misbehaving.  However, we should instead add a misbehaving field to getpeerinfo (ideally also including the last error), since this will be very useful both in regression tests and in the live network. And so let's move this periodic update of misbehaviors to somewhere common.

2020-04-06 20:38 UTC, gandrewstone commented on src/dosman.cpp
> +        double nNewMisBehavior =
if (nOldMisBehavior == 0.0) break;

Doing this would skip the pow and the atomic ops for this common case... perhaps its an optimization without proof of bottleneck, but in this case its very simple to implement.

2020-04-06 21:07 UTC, ptschip commented on src/dosman.cpp
> +    double prior = pNode->nMisbehavior.load();
fetch_add isn't available for floating point atomics until C++20

2020-04-06 21:11 UTC, ptschip commented on src/dosman.cpp
> +        double nNewMisBehavior =
done

2020-04-06 22:12 UTC, ptschip commented on src/qt/clientmodel.cpp
> +    // Update all misbehaviors
I'll create a new thread for running these updates every 10 secs.  BTW, banscore is already in getpeerinfo.  As for showing the last banreason, that would be more difficult to do and I'd like to leave that for a different PR.

2020-04-07 00:04 UTC, gandrewstone approved these changes

2020-04-07 00:04 UTC, gandrewstone commented
Note travis is green even though github did not update.

2020-04-07 00:04 UTC, merged