Request Manager fixes for out of order blocks , thinblocks and regtest workaround
gandrewstone/bitcoin pull request #312
Opened 2017-02-20 21:30 UTC by ptschip

Several items here:

Blocks are now requested in Request manager in the correct order, or rather the order than INV's were received.  This fixes some issues with regression tests and is  more efficient at connecting blocks because they no longer have to be written to disk, then read from disk to be connected.  

If two thinblocks are requested from the same peer, only one will actually be requested but the block source to the second will get deleted. This behavior would cause frequent hangups on regtest and cause block to be re-requested in the future.  Instead we do not delete the block source if we we're unable to actually make the request.

With the two fixes above the "regtest" workaround is no longer needed for the block re-request intterval.

2017-02-22 15:18 UTC, gandrewstone commented
I would like to see block download be more like bittorrent where blocks can be downloaded out-of-order like bittorrent file sections are pulled out of order.  This is the purpose of the request manager.  If subsystems (seems like most of them right now) can't handle out of order blocks, we could create a cache between the out of order download and the subsystem.  And then we can work to remove the ordering requirement in the subsystems.

This is important for several reasons:
1. We can't control when a block download completes, only when we request them.  So if there are block ordering issues we'd really need to request them serially.  This will have a big performance impact.
2. Serial block requests allow an "attacker" or slow node to DOS initial block download by offering a block but then sending it very slowly.  The request manager's retry logic does help mitigate this issue but does not entirely solve it.

So I think that the in-order block request part of this PR likely doesn't solve the problem, it just makes it less likely.  But it also makes it MUCH less likely in a very controlled single machine regtest environment (because there are no network bandwidth constraints), so we may be getting a skewed idea of its efficacy in a real network.  Instead, we need to ensure that blocks are presented to the system in order AFTER they are received.

2017-02-22 16:13 UTC, ptschip commented
@gandrewstone 

"So I think that the in-order block request part of this PR likely doesn't solve the problem, it just makes it less likely. But it also makes it MUCH less likely in a very controlled single machine regtest environment (because there are no network bandwidth constraints), so we may be getting a skewed idea of its efficacy in a real network. Instead, we need to ensure that blocks are presented to the system in order AFTER they are "

You are correct it doesn't necessarily solve it 100% of the time, but , close enough to be very valuable IMO.  It does fix the hangups during IBD, which is why it fixed the problems in regtest, because that is where we do a lot of IBD - we mine 100 blocks at a time and then sync...etc.  If you run the regression tests with this patch you'll see how we don't get any of the 5 second delays (which are 30 secs on mainnet)...and then run the regression tests without and you'll get a lot hick ups, most obviously seen in the very first regression test but they also happen in other tests as well.

But, there is another deeper issue with out of order blocks which can happen when two blocks are mined one just after the other, or lets say, during startup, where we are two blocks behind...then we request a block from different nodes, but the node giving us the first block disconnects and we end up getting the second block/header first.  That's a different issue that needs a different solution.  As you suggest , we need some sort of cache for that.  I think in this particular case though we would need to cache the headers, not the blocks...(as long as we have correctly linked headers then Bitcoin will already cache any blocks on disk without invalidating them).  But I think this other issue needs more discussion and a different PR for that.

2017-03-02 21:36 UTC, sickpig commented
https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/207134836#L1503

for some reason the last step of `make check` spent more than 10 minutes without producing any output, hence travis timed out. 

Is there anything in the code to justify the test to be so slow?

2017-03-02 21:46 UTC, ptschip commented
no, i didn't add any unit tests ...

On 02/03/2017 1:36 PM, Andrea Suisani wrote:
>
> https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/207134836#L1503
>
> for some reason the last step of |make check| spent more than 10
> minutes without producing any output, hence travis timed out.
>
> Is there anything in the code to justify the test to be so slow?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/312#issuecomment-283789812>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMRF0Mz8EtPStiRzhYNf-EMNbbHoVQoOks5rhzZ2gaJpZM4MGotP>.
>

2017-03-05 15:18 UTC, ptschip commented
once PR 333 is merged I can rebase this and take it out of WIP

2017-03-26 22:19 UTC, deadalnix requested changes

2017-03-26 22:19 UTC, deadalnix commented on src/requestManager.cpp
> +                   {
If you are going to fix indentation, at least do it right.

2017-03-26 22:19 UTC, deadalnix commented on src/requestManager.cpp
> +        }
Congratulation, you broken the whole indentation. Which is bad in itself, but has the added benefit of making the diff completely impossible to review. Please fix.

2017-03-26 22:19 UTC, deadalnix commented on src/requestManager.h
> +  // This keeps blocks from returning out of order.
Why is that a problem ?

2017-03-27 14:27 UTC, ptschip commented
now that we're fixing style globally, i'm going to take this indentation fix out...it's not really part of the PR anyway.

2017-03-27 14:48 UTC, ptschip commented on src/requestManager.h
> +  // This keeps blocks from returning out of order.
out of order blocks can and do cause unnecessary timeouts and re-requests during IBD.  Imagine you've just request 8 large blocks from a node, with the youngest block last...now you have to wait for all 8 blocks to download before you can connect any of them...now what if that node is also a slow downloader ...now you're stuck, when you could have been doing useful work , until you get a timeout and end up re-requesting the blocks from another node.   This doesn't solve all the problems to do with out of order blocks such as when two blocks are mined closely in time and inv's/headers show up out of order, however, it does solve the problem most often seen.

2017-04-05 07:39 UTC, sickpig commented
@gandrewstone is this PR ready to be committed? 

If yes I would vote also for a backport to `release` branch.

2017-05-20 02:29 UTC, ptschip commented
closing for now

2017-05-20 02:29 UTC, closed without merging