Remove Block Stalling code
gandrewstone/bitcoin pull request #403
Opened 2017-03-26 02:06 UTC by ptschip

Block stalling detection is no longer required since
the introduction of the Request Manager.

2017-03-26 02:50 UTC, ptschip commented
@gandrewstone do you want me to leave the code in but commented out , or just rip it out completely?

2017-03-26 08:58 UTC, ftrader commented
I see no tests have been modified. Was the block stalling code historically not covered by tests?

Is the request manager's 30 second stalling functionality covered by tests?

2017-03-26 10:34 UTC, ptschip commented
no stalling tests...none in core and none in bu that i'm aware of
...maybe i'm wrong but i don't think it's testable other than by running
IBD manually and seeing the re-requests happen.

On 26/03/2017 1:59 AM, freetrader wrote:
>
> I see no tests have been modified. Was the block stalling code
> historically not covered by tests?
>
> Is the request manager's 30 second stalling functionality covered by
> tests?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/403#issuecomment-289267361>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMRF0F8FWAU10ICvQHr5CNgFLpWcCZuKks5rpijUgaJpZM4MpSZy>.
>

2017-03-26 11:27 UTC, ftrader commented
>testable [...] by running IBD manually and seeing the re-requests happen

Yes, that sounds like a reasonable way to test it.

2017-03-26 21:46 UTC, deadalnix requested changes
There is no tests. Behavior changes should come with tests.

2017-03-26 21:46 UTC, deadalnix commented on src/main.cpp
> +    //  int64_t nStallingSince; // BU: no longer used
Do not comment out code, remove it if it needs to be removed.

2017-04-01 00:49 UTC, zquestz commented on src/main.cpp
> +    //  int64_t nStallingSince; // BU: no longer used
+1

2017-04-05 11:31 UTC, kyuupichan requested changes

2017-04-05 11:31 UTC, kyuupichan commented on src/main.cpp
> +    //  int64_t nStallingSince; // BU: no longer used
@gandrewstone as requested, I cannot see how this change can hurt given the assumption that the req. mgr. does the same job.

However I strongly agree with @deadalnix that the commented code should simply be removed.  Lots of commented code is immensely distracting and given everything is available in history I would much prefer to simply see the lines removed outright.

2017-04-08 12:49 UTC, kyuupichan approved these changes

2017-04-24 10:28 UTC, merged

2017-04-30 22:22 UTC, sickpig commented
@ptschip do you think we need to backport this one? (fwiw I think we should)

2017-05-01 11:12 UTC, ptschip commented
we really need to have SENDHEADERS merged first before doing
that...there is a case if thinblocks is turned off where stalling can be
a problem and still requires the blocks talling code until we have the
sendheaders PR which uses the request manager for this special case .

On 30/04/2017 3:22 PM, Andrea Suisani wrote:
>
> @ptschip <https://github.com/ptschip> do you think we need to backport
> this one? (fwiw I think we should)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/403#issuecomment-298261260>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMRF0PTjiHLiW2QtIKexQ_hsrl-o3AjZks5r1QmbgaJpZM4MpSZy>.
>