Remove useless argument to AlertNotify.
gandrewstone/bitcoin pull request #404
Opened 2017-03-26 23:13 UTC by deadalnix

As per title.

2017-03-27 08:09 UTC, sickpig requested changes
unrelated code change in `main.h`

2017-03-27 08:09 UTC, sickpig commented on src/main.h
> +extern bool fEnableReplacement;  // BU TODO is this RBF flag?
this change seems unrelated to this PR

2017-04-05 08:07 UTC, sickpig requested changes

2017-04-05 08:07 UTC, sickpig commented on src/main.cpp
> +    boost::thread t(runCommand, strCmd); // thread runs free
fix a trailing comment in a new PR?

2017-04-05 08:07 UTC, sickpig commented on src/main.h
> +extern bool fEnableReplacement;  // BU TODO is this RBF flag?
@deadalnix  as a pointed out already this change is unrelated to this PR.

2017-04-05 15:39 UTC, merged

2017-04-05 15:43 UTC, gandrewstone commented
no backport needed, AlertNotify is not in 1.0