[WIP] ensure a newly connected node has properly sync'd headers
gandrewstone/bitcoin pull request #409
Opened 2017-03-29 09:44 UTC by ptschip

Two additional measures to prevent sybil nodes from taking advantage of our node during initial sync. These are the last items I believe that are needed to prevent any of these types of attacks and builds on the work done in PR #356

-  Make sure that the sync height the node advertises is the actual
    height that we get when they connect.  If they are falsely advertising their
    sync height then we will disconnect and ban them.

-  Also, If a node trickles us headers during initial sync then give them a DOS

    A possible attacker could connect to our node during initial sync and
    trickle us the headers causing a much delayed sync, possibly increasing
    sync time by many days.  By giving them a DOS 20 for each infraction
    they will quickly be disconnected after a few downloads and allow
    another peer to be used to download the initial headers instead.

-  Still WIP as I'm working on unit tests for this and need PR406 merged first.

2017-04-06 08:33 UTC, cddjr requested changes

2017-04-06 08:33 UTC, cddjr commented on src/main.cpp
> +        else if (state.fSyncStarted && !state.fSyncCompleted)
else if (state.fSyncStarted && !state.fSyncCompleted **&& state.fFirstHeadersReceived**)

2017-04-07 13:06 UTC, ptschip commented on src/main.cpp
> +        else if (state.fSyncStarted && !state.fSyncCompleted)
@cddjr you are correct...thank you!

2017-05-08 23:47 UTC, ptschip commented
closing for now as not working on it right now.

2017-05-08 23:47 UTC, closed without merging