[WIP] Activate SENDHEADERS functionality
gandrewstone/bitcoin pull request #455
Opened 2017-04-17 22:47 UTC by ptschip

The commits are a bit of a mess...i'll squash them down soon enough but I want to add another set of python tests at the end.

@gandrewstone When ready, this PR should be merged prior or at the same time as the block stalling PR #403, since block stalling can be effected by sendheaders during a special case when thinblocks is turned off.

2017-04-18 18:11 UTC, ptschip commented
@gandrewstone taking this out of WIP and is ready for review.

2017-04-19 10:26 UTC, ftrader requested changes

2017-04-19 10:26 UTC, ftrader commented on qa/pull-tester/rpc-tests.py
> +    'sendheaders',
Something clearly went wrong with this change.

2017-04-19 10:33 UTC, ptschip commented
@ftrader oops I was doing a looping test for sendheaders and forgot to revert, fixed now.

2017-05-04 14:49 UTC, merged