Create expedited.cpp and move expedited code there
gandrewstone/bitcoin pull request #457
Opened 2017-04-20 01:26 UTC by ptschip

2017-04-20 12:26 UTC, sickpig commented
@gandrewstone  I wonder if we could add `expedited.{cpp,h}` to the `src/.formatted-files`

2017-04-20 15:23 UTC, ptschip commented
@sickpig thanks, i'll add those in to the list and push up.

2017-04-20 22:22 UTC, kyuupichan commented on src/expedited.h
> +extern CCriticalSection cs_xpedited;
Can you add a comment as to what precisely this critical section is intended to be protecting?

2017-04-20 22:34 UTC, ptschip commented on src/expedited.h
> +extern CCriticalSection cs_xpedited;
ok done

2017-04-20 23:00 UTC, kyuupichan requested changes
Apart from these minor points looks good to me.

2017-04-20 23:00 UTC, kyuupichan commented on src/expedited.cpp
> +
Is the using needed?  I see std:: throughout the file; let's be consistently explicit as that seems to be the trend.

2017-04-20 23:00 UTC, kyuupichan commented on src/expedited.cpp
> +
I think these variables should be static; no point exporting them as they're file-local.

2017-04-21 00:53 UTC, ptschip commented
@kyuupichan fixed your 2 issues and squashed them into the previous commit...also cleaned up and replaced the boost::lexical casts.

2017-04-21 01:03 UTC, ptschip commented
@kyuupichan in some cases also updated the use of error() messages instead of LogPrintf followed by return false.

2017-04-21 01:05 UTC, ptschip commented
i really hate the way clang-format will indent the variables by 4 but not the text for print statements, so we end up with a strange looking indentations for error() or logprintf()

2017-04-21 01:11 UTC, kyuupichan approved these changes

2017-04-25 14:19 UTC, ptschip commented
rebased

2017-04-26 23:29 UTC, ptschip commented
@gandrewstone there is some kind of intermittent crash in the exploit_tests.cpp...it's hard to find out what it is because it only happens on Travis.  Pushed up another attempt at a fix.

2017-04-27 12:16 UTC, gandrewstone commented
the exploit_tests.cpp travis issue isn't relevant to this PR AFAICT, so merging...

2017-04-27 12:16 UTC, merged