memory checking and profiling changes.
gandrewstone/bitcoin pull request #469
Opened 2017-04-24 12:23 UTC by gandrewstone

This patch adds the option to enable gperftools (heap profiler) to the build.
It also adds a RPC call that dumps the sizes of global structures at runtime.

It also cleans up some known 1 time allocations when Bitcoin shuts down, so the memory check results is easier to understand, and fixes a rare socket-left-open issue.

2017-04-24 12:38 UTC, sickpig commented on src/netbase.cpp
> +        }
seems unrelated for the scope of this PR

2017-04-24 12:38 UTC, sickpig commented on src/requestManager.cpp
> +        LogPrint("blk", "%s available at %s\n", obj.ToString().c_str(), from->addrName.c_str());
nit: didn't we decided to always use curly brackets?

2017-04-24 12:38 UTC, sickpig commented on src/stat.h
>      }
fix brackets alignment.

2017-04-24 12:43 UTC, ftrader commented on src/unlimited.cpp
> +//boost::thread_specific_ptr<LockStack> lockstack;
dead code

2017-04-24 12:45 UTC, sickpig commented
one last point the new RPC call should also add a unit test for it.

2017-04-24 19:24 UTC, greatwolf commented on src/requestManager.h
> +    //protected:
Why is this here?

2017-04-24 19:41 UTC, greatwolf commented on src/requestManager.cpp
>    if (std::find_if(availableFrom.begin(), availableFrom.end(), IsCNodeRequestDataThisNode(from)) == availableFrom.end())  // node is not in the request list
why not prefer the form `begin(availableFrom), end(availableFrom)`?
brace alignment needs fixing here too.

2017-04-24 19:57 UTC, greatwolf commented on src/unlimited.cpp
> +        mallocedStats.push_front(new CStatHistory<uint64_t >("net/recv/msg/" +  *i));
It's worth mentioning you can still shove this into a `unique_ptr` even if it is meant to last the program duration. In this case cleanup happens on shutdown, just either make it `static` or place it in global scope.

2017-04-24 20:00 UTC, greatwolf commented on src/unlimited.cpp
> +}
Prefer `= nullptr;`. Also see my comment above on `unique_ptr` which could make `UnlimitedCleanup` unnecessary unless the intent is to log this for statical purposes?

2017-04-24 20:09 UTC, greatwolf commented on src/unlimited.h
> +extern std::list<CStatBase*> mallocedStats;
What about just using a `stack` or `vector` for this? `push_back` `pop_back` exist for `vector` so you can still preserve cleanup order.

2017-04-24 20:13 UTC, greatwolf commented on src/requestManager.cpp
>      }
I know this part is mostly formatting and updating return type to fit method but this raw loop should be refactored into a `find_if` or using some std algorithm.

2017-04-24 20:56 UTC, gandrewstone commented on src/requestManager.cpp
>    if (std::find_if(availableFrom.begin(), availableFrom.end(), IsCNodeRequestDataThisNode(from)) == availableFrom.end())  // node is not in the request list
once the std:: is prefixed it becomes even longer.
I don't want to fix the braces as part of this PR.  Looks like the "janitor" is needed here as well as in the dev branch

2017-04-24 20:59 UTC, gandrewstone commented on src/unlimited.cpp
> +        mallocedStats.push_front(new CStatHistory<uint64_t >("net/recv/msg/" +  *i));
the problem is that I don't really know how many message types there will be (although I guess that this should be discoverable at compile time).  if I did know that I could use an array of unique_ptrs as you suggest, but I'm not sure if it makes much difference.

2017-04-24 20:59 UTC, gandrewstone commented on src/unlimited.cpp
> +}
"release" is not c++11

2017-04-24 21:04 UTC, gandrewstone commented on src/requestManager.cpp
>      }
maybe a separate PR.  This PR just changes the function to return true/false to clean up some unnecessarily verbose logging

2017-04-24 21:04 UTC, gandrewstone commented on src/requestManager.h
> +    //protected:
good catch, its was temporary, thanks!

2017-04-24 21:12 UTC, gandrewstone commented on src/requestManager.cpp
> +        LogPrint("blk", "%s available at %s\n", obj.ToString().c_str(), from->addrName.c_str());
IDK that we did.  I thought it was part of Allman style, but I guess its not.  Allman just covers placement of parens.  Personally I don't mind them.  But we should argue this out and update developer-notes.md.  Anyway I will fix here.

2017-04-24 21:17 UTC, gandrewstone commented on src/netbase.cpp
> +        }
I'll move this and the assert() fixes into its own PR

2017-04-24 22:27 UTC, gandrewstone commented on src/unlimited.h
> +extern std::list<CStatBase*> mallocedStats;
does it matter?  I suppose a vector would be smaller.  What other advantages are there?

2017-04-24 22:28 UTC, gandrewstone commented
note, pulled a few changes into their own PR and squashed down to 1 commit.

2017-04-24 22:34 UTC, greatwolf commented on src/unlimited.h
> +extern std::list<CStatBase*> mallocedStats;
Structurally it's simpler than a `list`, the addresses are guaranteed to be saved next to each other, could be useful later on if you want to examine the memory. It also removes the need to `#include <list>` which means less work for the compiler.

2017-04-25 19:01 UTC, greatwolf commented on src/unlimited.cpp
> +    ret.push_back(Pair("vNodes",vNodes.size()));
needs a space after comma.

2017-04-25 19:01 UTC, greatwolf commented on src/unlimited.cpp
> +    std::vector<CNode*>::iterator n;
why scope `n` outside the loop?

2017-04-25 19:08 UTC, greatwolf commented on src/unlimited.cpp
> +    {
You can reduce the lexical noise somewhat from `(*n)->..` to `n.` by declaring it as a `CNode &`.

2017-04-25 19:11 UTC, greatwolf commented on src/unlimited.cpp
> +        //node.push_back(Pair("", (*n)->.size()));
?

2017-04-25 19:55 UTC, greatwolf commented
Is clang-format currently being run as part of the workflow/build process? That will help make many of the formatting nitpicks a thing of the pass.

2017-04-25 20:09 UTC, gandrewstone commented
Taking this out of WIP.

clang-format is being run in dev and we will backport this functionality to release (@greatwolf would you like to take this on)?  Except for egregious cases, please let clang-format do its thing rather than note every small issue.  Look for substantive issues like "did I forget a structure?"

2017-04-28 17:03 UTC, ftrader reviewed
I have not tested this yet, but will try to do so over the next days.

One aspect I'm interested in is how to select / make sure that all the necessary structures are selected in getstructuresizes() .

2017-04-28 17:03 UTC, ftrader commented on src/requestManager.cpp
> +          LogPrint("blk", "%s available at %s\n", obj.ToString().c_str(), from->addrName.c_str());
This outputs peer IP address - guard with `logips` check?

2017-04-28 17:03 UTC, ftrader commented on src/unlimited.cpp
> +    //ret.push_back(Pair("lockstack",lockstack.size()));
not needed? perhaps rather document why instead of the commented code.

2017-04-28 17:03 UTC, ftrader commented on doc/developer-notes.md
> +Bitcoin Unlimited can be compiled with the libtcmalloc allocation library and
The configuration seems to only enable it for Linux at the moment. Maybe mentioned "can be compiled on Linux with the ..." .

It seems as if the library is [available on other platforms](https://github.com/gperftools/gperftools) - I suppose it's been enabled only for Linux initially due to testing resource scarcity.

2017-05-01 20:44 UTC, gandrewstone commented on doc/developer-notes.md
> +Bitcoin Unlimited can be compiled with the libtcmalloc allocation library and
yes I haven't tested on other platforms.

2017-05-01 20:47 UTC, gandrewstone commented on src/unlimited.cpp
> +    //ret.push_back(Pair("lockstack",lockstack.size()));
fixed

2017-05-01 22:06 UTC, gandrewstone commented on src/requestManager.cpp
> +          LogPrint("blk", "%s available at %s\n", obj.ToString().c_str(), from->addrName.c_str());
fixed

2017-05-01 23:03 UTC, gandrewstone commented on src/unlimited.h
> +extern std::list<CStatBase*> mallocedStats;
I hear you but I don't think that these issues are important enough for me spend the time to switch from list to vector.  If you'd like to switch it, go ahead!  You can check out my branch in your repo, and then issue a PR into my branch.  Or after this gets merged, do it the separately.

2017-05-02 10:06 UTC, ftrader commented on doc/developer-notes.md
> +Bitcoin Unlimited can be compiled with the libtcmalloc allocation library and
Adding a '... on Linux ...' in the documentation makes it clearer to people running on other platforms that this diagnostic feature isn't currently supported on their platforms.
That's why I raised this point.

2017-05-02 15:05 UTC, ftrader requested changes
I tested this PR on Ubuntu 16.10 x86_64.

It seems hard to determine whether documentation about the perftools is still up to date - the official docs I found were several years old.

Nevertheless, I was able to build, do a heap check run and a profiling run, and request the getstructuresizes data.

I had a look at the Makefile changes to verify that libtcmalloc was linked last (which it needs to be otherwise the heap checking may not work reliably).

So it looks ok to me - can you just fix the duplicate "vNodes" output in getstructuresizes please.

2017-05-02 15:05 UTC, ftrader commented on src/unlimited.cpp
> +    ret.push_back(Pair("vNodes", vNodes.size()));
Duplicate output of 'vNodes' - cf. line 1482

2017-05-03 02:15 UTC, gandrewstone commented
I fixed the duplicate vNodes and added a note that this is for linux only and squashed the commits in preparation for merging.  I will take ftrader's comment as a signoff as soon as the automated checks validate my squash commit.

2017-05-03 08:05 UTC, ftrader approved these changes

2017-05-03 12:59 UTC, merged