Re-request a full thinblock on merkleroot check failure
gandrewstone/bitcoin pull request #482
Opened 2017-04-27 04:28 UTC by ptschip

This is a stop gap measure for the time being until a more efficient
refactor can take place.

2017-04-29 03:28 UTC, kyuupichan requested changes

2017-04-29 03:28 UTC, kyuupichan commented on src/thinblock.cpp
> +        pfrom->PushMessage("getdata", vGetData);
Please use NetMsgType::GETDATA here (and at the other place in this file).

I approve with that change; and I think this should be considered for backport to release as it solves the banning DoS of #485 until we solve the collision issue.

2017-04-29 04:23 UTC, kyuupichan commented
I've been running this successfully for about an hour without issues.  Make check passes.  Of course, getting a bad merkleroot block hasn't happened, and might not for months.

2017-04-29 04:49 UTC, kyuupichan commented
Just happened:

https://hastebin.com/ufevudotoy.pas

The log message could do with a newline

2017-04-29 15:33 UTC, ptschip commented
@kyuppican

you're right,  i think i'm going refactor this whole thing anyway...as a
stop gap for us to keep testing it works fine but it does break our
re-request functionality.
although not much impact, we only do 1 or 2 rerequests a day anyway, but
still it's not really working the way it was intended.  I'll get on to
it once i finish the 486

On 28/04/2017 9:49 PM, Neil wrote:
>
> Just happened:
>
> https://hastebin.com/ufevudotoy.pas
>
> The log message could do with a newline
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/482#issuecomment-298147076>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMRF0CkrTL-w-IHI0Kwm30IFk8QFoY4_ks5r0sFPgaJpZM4NJtc8>.
>

2017-05-01 04:20 UTC, ptschip commented
@kyuupichan  I uploaded the refactor...you can run it as is, but it requires manual testing and in the morning I"ll upload the test scenarios I've been doing.   Basically what this refactor does is grabs all the full tx hashes and checks the merkle root before attempting to reconstruct the block.  This way we don't break our re-request functionality and everything works as it did before.

2017-05-01 09:47 UTC, sickpig commented
@ptschip travis is failing due to `parallel.py` not finishing (looping).

the auto clang format checking finding an inconsistency in `thinblock.cpp`, see:
https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/227503334#L1177

2017-05-01 12:18 UTC, ptschip commented
@sickpig updated the formatting...the issue with parallel.py is known..it's rare and is a bug in PV which i haven't had time to fix.

2017-05-01 12:29 UTC, ptschip commented
Added one more commit ...I beleive this PR is complete now and ready for review.

2017-05-02 07:22 UTC, kyuupichan commented on src/thinblock.cpp
> +            }
This block of code already exists around line 100 and again around line 360.  They should really be collapsed to one.

2017-05-02 07:22 UTC, kyuupichan commented on src/thinblock.cpp
> +        count++;
count appears unused?

2017-05-02 07:22 UTC, kyuupichan commented on src/thinblock.cpp
> +        count++;
What does it mean if it is end?

2017-05-02 13:48 UTC, ptschip commented
After much discussion with @kyuupichan I'm reverting this to the original single commit.

2017-05-02 20:21 UTC, kyuupichan approved these changes

2017-05-02 20:49 UTC, ptschip commented
just rebasing on 504 to get rid of this test crash error.

2017-05-02 22:41 UTC, kyuupichan commented
@ptschip I think the rebase lost my change

2017-05-02 22:45 UTC, ptschip commented
@kyuupichan that's very strange...do you want to rebumit..i'll merge again.

2017-05-02 22:46 UTC, ptschip commented
oh, i see i didn't pull down your merge first before i rebased , resubmit and i'll merge again.

2017-05-02 23:58 UTC, kyuupichan approved these changes

2017-05-03 18:05 UTC, merged