Factor out information unit formatting
gandrewstone/bitcoin pull request #548
Opened 2017-05-09 19:03 UTC by awemany

There's a couple places where a floating point amount of bytes is
formatted  with units attached (KB, MB, ...).

This factors all of them out and puts them into a single function
static string formatInfoUnit(double).

It also fixes a couple potential array-out-of-bounds-access errors,
as none of the upper bounds had been checked before.

2017-05-10 04:12 UTC, kyuupichan requested changes

2017-05-10 04:12 UTC, kyuupichan commented on src/thinblock.cpp
> +    while (value > 1000.0 && i < 7)
7 should not be hard-coded.  0...6 is probably enough anyway, no need for the ZB and YB

2017-05-10 10:04 UTC, awemany commented
@kyuupichan : Removed ZB and YB, calculated upper bound from array size.
@ftrader : Added unit test for formatInfoUnit(..).

2017-05-10 10:08 UTC, kyuupichan approved these changes

2017-05-10 14:14 UTC, ftrader commented
I'm not a great fan of retaining the decimal point with only trailing zeroes (.00), they convey no info to me, but that's a niggle and I'm fine with the changes.

2017-05-10 14:15 UTC, ftrader approved these changes

2017-05-10 17:29 UTC, gandrewstone commented on src/thinblock.cpp
> +        value = 0.0;
I'm concerned about mis-displaying negative numbers, even if we don't have them right now.  I think you can make it work by removing the above test and using while ((value < -1000.0 || value > 1000.0) .  Can you try it and extend the tests to negatives?

2017-05-10 17:30 UTC, gandrewstone commented on src/thinblock.h
> +extern std::string formatInfoUnit(double value);
add a docstring comment describing the operation of this function.  See https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/release/doc/developer-notes.md#doxygen-comments

2017-05-10 20:49 UTC, awemany commented on src/thinblock.cpp
> +        value = 0.0;
Ok so you want -10000 be displayed at -10.00KB for example?

Sure I can do that. Now I just wonder: does it make sense to move the whole function somewhere else, like generic util.cpp, or unlimited.cpp?

Or is it fine where it is?

2017-05-11 17:44 UTC, awemany commented
@gandrewstone: Addressed your points, hopefully to your liking. Also added the test to the list of properly formatted files.

2017-05-11 19:41 UTC, awemany commented
The failure is in parallel.py on just one build - all others are fine, if I interpret the travis stats correctly.

I fail to see how this is related to my code. Might this be a spurious failure (race?) in the parallel validation code? @ptschip?

I updated my code to add formatting for negative values and added comments - I can't see how that might have created this failure. I *also* updated to the most current `dev` branch HEAD.

2017-05-11 19:57 UTC, gandrewstone commented
looks great, I'll commit as soon as tests pass

2017-05-11 22:35 UTC, merged