[WIP] Improve uncaching of coins
gandrewstone/bitcoin pull request #817
Opened 2017-10-28 18:03 UTC by ptschip

There are several improvements to make now that we are able to trim the coins cache regularly.  In this PR we only uncache coins if they were not accepted to the mempool, trimmed from the orphans cache, or trimmed later by the mempool.  This way we can keep the coins cache as full as possible with relevant coins and prevent any obscure attacks whereby out coins cache could get randomly trimmed of useful coins.

2017-12-07 16:50 UTC, ptschip commented
@gandrewstone  I finally got the unit tests to work properly, this PR is ready for review.

2017-12-08 15:26 UTC, gandrewstone requested changes

2017-12-08 15:26 UTC, gandrewstone commented on src/main.cpp
> +                    *pfMissingInputs = true;
pfMissingInputs is sometimes passed as NULL.  Its an optional parameter.

2017-12-08 15:26 UTC, gandrewstone commented on src/main.cpp
> +                return false;
Also, this code assumes that the *pfMissingInputs was passed to this function preloaded with false...

EDIT: I see that you changed some of the callers to require this variable and you set it to false.  I think that doing it this way is error prone.  Callers will not call AcceptToMempool properly.  Instead, why not use a temporary?

2017-12-08 17:02 UTC, ptschip commented on src/main.cpp
> +                return false;
yes you're right...I just pushed up 3  new commits which handle a NULL if passed and also reverts some of the other cases.

2017-12-08 17:17 UTC, ptschip commented on src/main.cpp
> +                    *pfMissingInputs = true;
fixed

2017-12-08 17:17 UTC, ptschip commented on src/main.cpp
> +                return false;
you're right, fixed.  look at the last 3 commits

2017-12-19 14:16 UTC, merged